### ISSUE TITLE
Pick base image or Dockerfile when using internal/docker-push 

### ISSUE THREAD

**Issue by azr** [wercker/support#63]
Hello there,

I'd like to use a specific base for my docker image

```
    - internal/docker-push:
        username: _token
        password: $GCR_AUTH_TOKEN
        repository: gcr.io/$GCLOUD_PROJECT/app
        registry: https://gcr.io
        image: centurylink/ca-certs # ?
        from: centurylink/ca-certs # ?
        ports: "8080"
        entrypoint: "/app"
```

**Comment by azr** [comment]
Also it would be nice to have a list of available options !

**Comment by vially** [comment]
The `internal/docker-push` step is pushing the image defined by the `box` attribute of your `wercker.yml`. Therefore this can be the image used in either the `build` or `deploy` pipeline.

If you want to push the `centurylink/ca-certs` image you would need something like this in your `wercker.yml`:

```yaml
deploy:
  box: centurylink/ca-certs
  steps:
    - internal/docker-push:
        username: _token
        password: $GCR_AUTH_TOKEN
        repository: gcr.io/$GCLOUD_PROJECT/app
        registry: https://gcr.io
        ports: "8080"
        entrypoint: "/app"
```

[Official docs](http://devcenter.wercker.com/docs/containers/pushing-containers.html) for the `internal/docker-push` step.

Hope this helps.

**Comment by azr** [comment]
Hello @vially,

okay get it, thanks for your answer !

I have another question : my build created an executable named "/app".

But when starting the image I get an "app" not found error.

Can't I send files to this docker build ? That'd be nice :)

**Comment by vially** [comment]
> Can't I send files to this docker build?

You should be able to _send_ files to this docker build. You can do this using the wercker steps. Basically the wercker's `script` step is equivalent to the docker `RUN` command and all your code is already cloned for you in the current working directory. 

> I get an "app" not found error

I've been bitten by a similar problem a few days ago. In my case it was because I was building my image in the `build` pipeline but I had the `internal/docker-push` step defined in the `deploy` pipeline. And the way wercker seems to work right now is that it uses two different images for the `build` and the `deploy` pipeline.

The way I've fixed it is by moving the `internal/docker-push` step into the `build` pipeline.
I'm not sure if what you're experiencing is exactly the same problem though.

**Comment by azr** [comment]
@vially I think there is a problem there, because I want to deploy the smallest possible image that can handle ssl. It currently is `enturylink/ca-certs` (scratch + ca-certs). plus my app

But it also seems that these steps cannot be performed on anything else than a *google/cloud-sdk* box:
```
deploy:
  box: google/cloud-sdk
  steps:
    - script:
        name: install jq
        code: wget -O /usr/local/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.5rc1/jq-linux-x86_64-static && chmod a+x /usr/local/bin/jq
    - script:
        name: gcr.io authentication
        code: |
          export CLOUDSDK_CORE_DISABLE_PROMPTS=true
          gcloud auth activate-refresh-token $GCLOUD_ACCOUNT $GCLOUD_REFRESH_TOKEN
          gcloud config set project $GCLOUD_PROJECT
          gcloud config set compute/zone $GCLOUD_ZONE
          gcloud preview docker --authorize_only
          export GCR_AUTH_TOKEN=$(cat $HOME/.dockercfg | jq --raw-output '.["https://gcr.io"].auth' | base64 --decode | cut -d ':' -f2)
```
Because on scratch there is like nothing installed.

It'd be nice if the deploy step would be using a different box from the push step ?!

Or have I misunderstood something ?

**Comment by vially** [comment]
I think you could try something like this. Build your `app` in the `build` pipeline and then copy it to the `WERCKER_OUTPUT_DIR` which will make it available in the `deploy` pipeline as well. Then try exporting the `GCR_AUTH_TOKEN` in the `build` pipeline and **maybe** it will be available in the `deploy` pipeline as well. If the variable is not persisted between the pipelines then you could write `GCR_AUTH_TOKEN` to a file from the `build` pipeline and read it from the file in the `deploy` pipeline. For example:

```yaml
build:
  box: google/cloud-sdk
  steps:
    - script:
        name: gcr.io authentication
        code: |
          export CLOUDSDK_CORE_DISABLE_PROMPTS=true
          gcloud auth activate-refresh-token $GCLOUD_ACCOUNT $GCLOUD_REFRESH_TOKEN
          gcloud config set project $GCLOUD_PROJECT
          gcloud config set compute/zone $GCLOUD_ZONE
          gcloud preview docker --authorize_only
          export GCR_AUTH_TOKEN=$(cat $HOME/.dockercfg | jq --raw-output '.["https://gcr.io"].auth' | base64 --decode | cut -d ':' -f2)
          echo $GCR_AUTH_TOKEN > $WERCKER_OUTPUT_DIR/gcr_token
deploy:
  box: centurylink/ca-certs
  steps:
    - script:
        name: gcr.io authentication
        code: export GCR_AUTH_TOKEN=$(cat gcr_token)
    - internal/docker-push:
        username: _token
        password: $GCR_AUTH_TOKEN
        repository: gcr.io/$GCLOUD_PROJECT/app
        registry: https://gcr.io
        ports: "8080"
        entrypoint: "/app"
```

Although I haven't tried it but it might be worth a shot.

**Comment by azr** [comment]
This won't do it because I need a `google/golang` box with the golang toolchain installed to build my app's executable.

**Comment by vially** [comment]
But you can use any box for the `build` pipeline. Just make sure to install manually the `Google Cloud SDK` in a script step.

**Comment by vially** [comment]
Also, you might use the `internal/docker-scratch-push` step as an alternative to the `centurylink/ca-certs` image (I can't seem to find any official docs for it but it's mentioned in a tutorial on the [CoreOS blog](https://coreos.com/blog/building-minimal-containers-with-quay-kubernetes-wercker/)).

**Comment by azr** [comment]
No, both of those solution will kill the goodness of docker, the build time, and I have to maintain stuff.

We are a startup we already lost too much time hacking around this unfinished solution.

Sorry about your time and thanks for your answers.

**Comment by flenter** [comment]
@azr The issue I think with no executable named `/app ` is that by default wercker does not put content in the root of your container. We use `$WERCKER_SOURCE_DIR` (usually pointing to `/pipeline/source`). If you add a step that moves the file, this issue should be resolved:

```
  steps:
    - script:
        name: move app to root
        code: mv ./app /
```

**Comment by azr** [comment]
@flenter Yup, this did it, thanks for your answer !

We still have a problem about deploying a whole *google/debian + stuff* image just to run a binary.

I guess we will just use this one and wait until we have time for a better solution !

Thanks again @flenter and @vially !

**Comment by Tonnu** [comment]
@azr You could look into using one of the several [base-images](https://docs.docker.com/articles/baseimages/). I could also recommend looking into the `phusion/baseimage` hosted on Dockerhub. It provides a nice starting environment to run your app. 

Lastly, should you be using Go, you can statically compile your binary to not use any dynamic dependencies at runtime together with a 'scratch' container. We made a blogpost about deploying a scratch container to Kubernetes, but the gist of it should be generally applicable: http://blog.wercker.com/2015/06/23/Deploying-minimal-containers-to-kubernetes.html

Hope this helps!

**Comment by azr** [comment]
Hello @Tonnu,

That looks very interesting thanks.

I am already building a statically linked image of my app, the problem is I have to handle https, and to handle https I have to copy a ca-certs file into the container. Can we copy files when using `internal/docker-scratch-push` ? ( We don't want to add this file in the source code ).

The other problem is I want to push my docker images to google and it seems they do not handle username/password auth, yet...

**Comment by Tonnu** [comment]
Hi @azr, 

The way I see it is you have two options:

1. Save the contents of your ca-certs file in an env var. In a deploy step you could then extract it again and store it in the `$WERCKER_ROOT` directory. Everything in this directory gets copied to the scratch container.

2. Host your file somewhere else (like S3) and download it during a deploy step to the same `$WERCKER_ROOT` directory. 

Hope this helps! Here are some more useful links: 

http://devcenter.com/quickstarts/advanced/building-minimal-containers-with-go.html
http://devcenter.wercker.com/docs/steps/internal-steps.html
http://devcenter.wercker.com/docs/containers/pushing-containers.html (contains a step to push to google container registry)

Cheers!

**Comment by selaromi** [comment]
Hello! Can anyone help me? I'm building my container and testing it perfectly with wercker, but now I want to rebuild it and send it over to my docker registry in gcr.io. This is my wercker.yml. The most I've been able to do is upload the whole google/cloud-skd with my code inside :(

```
# This references the default Ruby container from
# the Docker Hub.
# https://registry.hub.docker.com/_/ruby/
# If you want to use a specific version you would use a tag:
# ruby:2.2.2
box: ruby:2.2.2-slim
# You can also use services such as databases. Read more on our dev center:
# http://devcenter.wercker.com/docs/services/index.html
services:
   - id: postgres
     env:
       POSTGRES_PASSWORD: $APP_POSTGRES_PASSWORD
       POSTGRES_USER: $APP_POSTGRES_USER
       POSTGRES_DB: $APP_POSTGRES_DB

# This is the build pipeline. Pipelines are the core of wercker
# Read more about pipelines on our dev center
# http://devcenter.wercker.com/docs/pipelines/index.html
build:
    steps:
        - script:
            name: echo ruby information
            code: |
                echo "ruby version $(ruby --version) running!"
                echo "from location $(which ruby)"
                echo -p "gem list: $(gem list)"
        - script:
            name: Initialize packages
            code: |
                apt-get update -qq && \
                        apt-get install -y \
                        build-essential \
                        git \
                        libpq-dev \
                        checkinstall \
                        libx11-dev \
                        libxext-dev \
                        zlib1g-dev \
                        libpng12-dev \
                        libjpeg-dev \
                        imagemagick
        - bundle-install
        - script:
            name: create db
            code: bundle exec rake db:create RAILS_ENV=test
        - script:
            name: migrate db
            code: bundle exec rake db:migrate RAILS_ENV=test
        - script:
            name: rspec
            code: bundle exec rake spec RAILS_ENV=test
        - script:
            name: code-climate
            code: rubycritic -p $WERCKER_REPORT_ARTIFACTS_DIR/coverage/ app

    after-steps:
        - wantedly/pretty-slack-notify:
            webhook_url: $SLACK_WEBHOOK_URL
            channel: development
deploy:
  box: google/cloud-sdk
  steps:
    - script:
        name: install jq
        code: wget -O /usr/local/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.5rc1/jq-linux-x86_64-static && chmod a+x /usr/local/bin/jq
    - script:
        name: gcr.io authentication
        code: |
          gcloud auth activate-refresh-token $GCLOUD_ACCOUNT $GCLOUD_REFRESH_TOKEN
          gcloud docker --authorize-only
          export GCR_AUTH_TOKEN=$(cat $HOME/.dockercfg | jq --raw-output '.["https://gcr.io"].auth' | base64 --decode | cut -d ':' -f2)
    - script:
        name: create tag
        code: export TAG=`date +%Y%m%d%H%M%S`
    - internal/docker-push:
        username: _token
        password: $GCR_AUTH_TOKEN
        repository: eu.gcr.io/concise-complex-104208/users
        tag: $TAG
        registry: https://eu.gcr.io
```

How do I specify the image I want to build is that of my own code and not the one from the box? I have tried removing the box and installing the dependencies inside my build process, but that doesn't do it either.

Thanks all!

**Comment by vially** [comment]
In order to push an image containing your code you would need to add the `internal/docker-push` step to the `build` pipeline rather than the `deploy` pipeline.

As a side note, it seems that you are pushing to the `eu.gcr.io` repository but you're reading the auth token of the more generic `gcr.io` region. I'm not sure if that should cause any issues but you might want to fix this by replacing:

```shell
export GCR_AUTH_TOKEN=$(cat $HOME/.dockercfg | jq --raw-output '.["https://gcr.io"].auth' | base64 --decode | cut -d ':' -f2)
```

with

```shell
export GCR_AUTH_TOKEN=$(cat $HOME/.dockercfg | jq --raw-output '.["https://eu.gcr.io"].auth' | base64 --decode | cut -d ':' -f2)
```

**Comment by selaromi** [comment]
hello @vially , thanks.

The problem with that is that I don't want to push a new image every time i create a build on any branch, only when a new push is added to the master branch.

**Comment by Morriz** [comment]
@vially How can I add the docker-push step to the build phase without specifying a new box (which would defeat the purpose)? gcloud needs to come from somewhere, and I have not found a way to install it unattended...

**Comment by vially** [comment]
@Morriz I've created a custom [gcr-auth step](https://github.com/vially/wercker-step-gcr-auth) which works on any box without having to install gcloud components. Maybe this will help?

**Comment by azr** [comment]
Nice one @vially, also be carefull when providing info like this : 

https://github.com/vially/gauthtoken/blob/master/main.go

( if I were you I'd remove the commit and allow for more settings )

**Comment by Morriz** [comment]
Tnxalot, you saved my day!

**Comment by Morriz** [comment]
Jah, you have to do things in the right order, and understand where the base image is used. Docker push wraps up the build artefacts in the latest specified container, which you can choose during deploy phase as well. I just choose a *-slim version of my provider (nodejs), which then picks up the the artefacts from the previous pipeline. I suggest copying what you need to $WERCKER_OUTPUT_DIR (in build phase) to be as lean as possible.

I believe wercker has an item about this on their blog somewhere.

Anyway, this way it's only possible to docker-push during deploy phase, but lean as possible.

**Comment by Tonnu** [comment]
@ernoaapa we're working on the new Workflows feature which will allow you to chain pipelines more then once so you'll be able to push to the registry and then trigger a deploy to kubernetes. If you're interested in beta-testing this, please shoot me an e-mail at toon@wercker.com. Cheers!
